/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "MapNode"
 */
package com.hisense.hiatmp.asn.v2x.Map;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

public class Node {

    public final static AsnType TYPE = Map.type(196612);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(Node.class);
        AsnConverter nameConverter = DescriptiveName.CONV;
        AsnConverter idConverter = NodeReferenceID.CONV;
        AsnConverter refPosConverter = Position3D.CONV;
        AsnConverter inLinksConverter = LinkList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{nameConverter, idConverter, refPosConverter, inLinksConverter});
    }

    @Null
    @Component(0)
    public String name;    /* OPTIONAL */
    @NotNull
    @Component(1)
    public NodeReferenceID id;
    @NotNull
    @Component(2)
    public Position3D refPos;
    @Null
    @Component(3)
    public Vector<Link> inLinks;    /* OPTIONAL */

    public static Node ber_decode(InputStream in) throws IOException {
        return (Node) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static Node per_decode(boolean align, InputStream in) throws IOException {
        return (Node) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Node)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
