package org.v2x.time;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.annotations.ASN1BoxedType;
import org.bn.annotations.ASN1Integer;
import org.bn.annotations.constraints.ASN1ValueRangeConstraint;


/**
 * @author zhangyong
 */
@ASN1BoxedType(name = "DMonth")
public class DMonth {

    @ASN1Integer(name = "DMonth")
    @ASN1ValueRangeConstraint(
            min = 0L,
            max = 12L
    )
    private Integer value;

    public DMonth() {
    }

    public DMonth(Integer value) {
        this.value = value;
    }

    public Integer getValue() {
        return this.value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

}
            