/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "VehSafetyExt"
 */
package com.hisense.hiatmp.asn.v2x.BSM;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class VehicleSafetyExtensions {

    public final static AsnType TYPE = BSM.type(655402);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(VehicleSafetyExtensions.class);
        AsnConverter eventsConverter = VehicleEventFlags.CONV;
        AsnConverter pathHistoryConverter = PathHistory.CONV;
        AsnConverter pathPredictionConverter = PathPrediction.CONV;
        AsnConverter lightsConverter = ExteriorLights.CONV;
        CONV.setComponentConverters(new AsnConverter[]{eventsConverter, pathHistoryConverter, pathPredictionConverter, lightsConverter});
    }

    @Null
    @Component(0)
    public VehicleEventFlags events;    /* OPTIONAL */
    @Null
    @Component(1)
    public PathHistory pathHistory;    /* OPTIONAL */
    @Null
    @Component(2)
    public PathPrediction pathPrediction;    /* OPTIONAL */
    @Null
    @Component(3)
    public ExteriorLights lights;    /* OPTIONAL */

    public static VehicleSafetyExtensions ber_decode(InputStream in) throws IOException {
        return (VehicleSafetyExtensions) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static VehicleSafetyExtensions per_decode(boolean align, InputStream in) throws IOException {
        return (VehicleSafetyExtensions) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof VehicleSafetyExtensions)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
