/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "VehSize"
 */
package com.hisense.hiatmp.asn.v2x.BSM;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class VehicleSize {

    public final static AsnType TYPE = BSM.type(524323);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(VehicleSize.class);
        AsnConverter widthConverter = VehicleWidth.CONV;
        AsnConverter lengthConverter = VehicleLength.CONV;
        AsnConverter heightConverter = VehicleHeight.CONV;
        CONV.setComponentConverters(new AsnConverter[]{widthConverter, lengthConverter, heightConverter});
    }

    @NotNull
    @Component(0)
    public Integer width;
    @NotNull
    @Component(1)
    public Integer length;
    @Null
    @Component(2)
    public Integer height;    /* OPTIONAL */

    public static VehicleSize ber_decode(InputStream in) throws IOException {
        return (VehicleSize) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static VehicleSize per_decode(boolean align, InputStream in) throws IOException {
        return (VehicleSize) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof VehicleSize)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
