/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "MapLink"
 */
package com.hisense.hiatmp.asn.v2x.MapNode;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class Movement {

    public final static AsnType TYPE = MapNode.type(196649);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(Movement.class);
        AsnConverter remoteIntersectionConverter = NodeReferenceID.CONV;
        AsnConverter phaseIdConverter = PhaseID.CONV;
        CONV.setComponentConverters(new AsnConverter[]{remoteIntersectionConverter, phaseIdConverter});
    }

    @NotNull
    @Component(0)
    public NodeReferenceID remoteIntersection;
    @Null
    @Component(1)
    public Integer phaseId;    /* OPTIONAL */

    public static Movement ber_decode(InputStream in) throws IOException {
        return (Movement) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static Movement per_decode(boolean align, InputStream in) throws IOException {
        return (Movement) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof Movement)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
