/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "MapSpeedLimit"
 */
package com.hisense.hiatmp.asn.v2x.MapNode;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class RegulatorySpeedLimit {

    public final static AsnType TYPE = MapNode.type(262156);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(RegulatorySpeedLimit.class);
        AsnConverter typeConverter = SpeedLimitType.CONV;
        AsnConverter speedConverter = Speed.CONV;
        CONV.setComponentConverters(new AsnConverter[]{typeConverter, speedConverter});
    }

    @NotNull
    @Component(0)
    public SpeedLimitType type;
    @NotNull
    @Component(1)
    public Integer speed;

    public static RegulatorySpeedLimit ber_decode(InputStream in) throws IOException {
        return (RegulatorySpeedLimit) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static RegulatorySpeedLimit per_decode(boolean align, InputStream in) throws IOException {
        return (RegulatorySpeedLimit) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof RegulatorySpeedLimit)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
