package org.v2x.rsi;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1Sequence;
import org.v2x.map.node.NodeReferenceID;


/**
 * @author zhangyong
 */
@ASN1Sequence(name = "ReferenceLink", isSet = false)
public class ReferenceLink {

    @ASN1Element(name = "upstreamNodeId", isOptional = false, hasTag = false, hasDefaultValue = false)
    private NodeReferenceID upstreamNodeId = null;

    @ASN1Element(name = "downstreamNodeId", isOptional = false, hasTag = false, hasDefaultValue = false)
    private NodeReferenceID downstreamNodeId = null;

    @ASN1Element(name = "referenceLanes", isOptional = true, hasTag = false, hasDefaultValue = false)
    private ReferenceLanes referenceLanes = null;


    public NodeReferenceID getUpstreamNodeId() {
        return this.upstreamNodeId;
    }


    public void setUpstreamNodeId(NodeReferenceID value) {
        this.upstreamNodeId = value;
    }


    public NodeReferenceID getDownstreamNodeId() {
        return this.downstreamNodeId;
    }


    public void setDownstreamNodeId(NodeReferenceID value) {
        this.downstreamNodeId = value;
    }


    public ReferenceLanes getReferenceLanes() {
        return this.referenceLanes;
    }

    public void setReferenceLanes(ReferenceLanes value) {
        this.referenceLanes = value;
    }

    public boolean isReferenceLanesPresent() {
        return this.referenceLanes != null;
    }
}
            