/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "RSI"
 */
package com.hisense.hiatmp.asn.v2x.RSI;

import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.ReflectionEnumeratedConverter;
import org.asnlab.asndt.runtime.type.AsnType;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public enum EventSource {
    unknown(0),
    police(1),
    government(2),
    meteorological(3),
    internet(4),
    detection(5);

    public final static AsnType TYPE = RSI.type(65538);
    public final static AsnConverter CONV;

    static {
        CONV = new ReflectionEnumeratedConverter(EventSource.class);
    }

    private int value;

    private EventSource(int value) {
        this.value = value;
    }

    public static EventSource valueOf(int value) {
        EventSource[] values = values();
        for (int i = 0; i < values.length; i++) {
            if (values[i].value == value) {
                return values[i];
            }
        }
        throw new IllegalArgumentException("No enum const value for " + value);
    }

    public static EventSource ber_decode(InputStream in) throws IOException {
        return (EventSource) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static EventSource per_decode(boolean align, InputStream in) throws IOException {
        return (EventSource) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public int value() {
        return value;
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
