/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "RSI"
 */
package com.hisense.hiatmp.asn.v2x.RSI;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

public class ReferencePath {

    public final static AsnType TYPE = RSI.type(65571);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(ReferencePath.class);
        AsnConverter activePathConverter = PathPointList.CONV;
        AsnConverter pathRadiusConverter = Radius.CONV;
        CONV.setComponentConverters(new AsnConverter[]{activePathConverter, pathRadiusConverter});
    }

    @NotNull
    @Component(0)
    public Vector<PositionOffsetLLV> activePath;
    @NotNull
    @Component(1)
    public Integer pathRadius;

    public static ReferencePath ber_decode(InputStream in) throws IOException {
        return (ReferencePath) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static ReferencePath per_decode(boolean align, InputStream in) throws IOException {
        return (ReferencePath) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof ReferencePath)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
