/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "RSI"
 */
package com.hisense.hiatmp.asn.v2x.RSI;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

/**
 * @author zhangyong
 */
public class RoadSideInformation {

    public final static AsnType TYPE = RSI.type(65587);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(RoadSideInformation.class);
        AsnConverter msgCntConverter = MsgCount.CONV;
        AsnConverter moyConverter = MinuteOfTheYear.CONV;
        AsnConverter idConverter = OctetStringConverter.INSTANCE;
        AsnConverter refPosConverter = Position3D.CONV;
        AsnConverter rtesConverter = RTEList.CONV;
        AsnConverter rtssConverter = RTSList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{msgCntConverter, moyConverter, idConverter, refPosConverter, rtesConverter, rtssConverter});
    }

    @NotNull
    @Component(0)
    public Integer msgCnt;
    @Null
    @Component(1)
    public Integer moy;    /* OPTIONAL */
    @NotNull
    @Size(min = 8, max = 8)
    @Component(2)
    public byte[] id;
    @NotNull
    @Component(3)
    public Position3D refPos;
    @Null
    @Component(4)
    public Vector<RTEData> rtes;    /* OPTIONAL */
    @Null
    @Component(5)
    public Vector<RTSData> rtss;    /* OPTIONAL */

    public static RoadSideInformation ber_decode(InputStream in) throws IOException {
        return (RoadSideInformation) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static RoadSideInformation per_decode(boolean align, InputStream in) throws IOException {
        return (RoadSideInformation) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof RoadSideInformation)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
