package org.v2x.spat;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.annotations.ASN1BitString;
import org.bn.annotations.ASN1BoxedType;
import org.bn.annotations.constraints.ASN1SizeConstraint;
import org.bn.types.BitString;

/**
 * @author zhangyong
 */

@ASN1BoxedType(name = "IntersectionStatusObject")
public class IntersectionStatusObject {

    @ASN1BitString(name = "IntersectionStatusObject")
    @ASN1SizeConstraint(max = 16L)
    private BitString value = null;

    public IntersectionStatusObject() {
    }

    public IntersectionStatusObject(BitString value) {
        this.value = value;
    }

    public BitString getValue() {
        return this.value;
    }

    public void setValue(BitString value) {
        this.value = value;
    }

}
            