/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "DefMotion"
 */
package com.hisense.hiatmp.asn.v2x.VehSafetyExt;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class MotionConfidenceSet {

    public final static AsnType TYPE = VehSafetyExt.type(196632);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(MotionConfidenceSet.class);
        AsnConverter speedCfdConverter = SpeedConfidence.CONV;
        AsnConverter headingCfdConverter = HeadingConfidence.CONV;
        AsnConverter steerCfdConverter = SteeringWheelAngleConfidence.CONV;
        CONV.setComponentConverters(new AsnConverter[]{speedCfdConverter, headingCfdConverter, steerCfdConverter});
    }

    @Null
    @Component(0)
    public SpeedConfidence speedCfd;    /* OPTIONAL */
    @Null
    @Component(1)
    public HeadingConfidence headingCfd;    /* OPTIONAL */
    @Null
    @Component(2)
    public SteeringWheelAngleConfidence steerCfd;    /* OPTIONAL */

    public static MotionConfidenceSet ber_decode(InputStream in) throws IOException {
        return (MotionConfidenceSet) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static MotionConfidenceSet per_decode(boolean align, InputStream in) throws IOException {
        return (MotionConfidenceSet) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof MotionConfidenceSet)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
