/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "VehSafetyExt"
 */
package com.hisense.hiatmp.asn.v2x.VehSafetyExt;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class PathHistoryPoint {

    public final static AsnType TYPE = VehSafetyExt.type(327734);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(PathHistoryPoint.class);
        AsnConverter llvOffsetConverter = PositionOffsetLLV.CONV;
        AsnConverter timeOffsetConverter = TimeOffset.CONV;
        AsnConverter speedConverter = Speed.CONV;
        AsnConverter posAccuracyConverter = PositionConfidenceSet.CONV;
        AsnConverter headingConverter = CoarseHeading.CONV;
        CONV.setComponentConverters(new AsnConverter[]{llvOffsetConverter, timeOffsetConverter, speedConverter, posAccuracyConverter, headingConverter});
    }

    @NotNull
    @Component(0)
    public PositionOffsetLLV llvOffset;
    @NotNull
    @Component(1)
    public Integer timeOffset;
    @Null
    @Component(2)
    public Integer speed;    /* OPTIONAL */
    @Null
    @Component(3)
    public PositionConfidenceSet posAccuracy;    /* OPTIONAL */
    @Null
    @Component(4)
    public Integer heading;    /* OPTIONAL */

    public static PathHistoryPoint ber_decode(InputStream in) throws IOException {
        return (PathHistoryPoint) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static PathHistoryPoint per_decode(boolean align, InputStream in) throws IOException {
        return (PathHistoryPoint) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof PathHistoryPoint)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
