/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "DefPosition"
 */
package com.hisense.hiatmp.asn.v2x.VehSafetyExt;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class Position3D {

    public final static AsnType TYPE = VehSafetyExt.type(131081);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(Position3D.class);
        AsnConverter latConverter = Latitude.CONV;
        AsnConverter long_Converter = Longitude.CONV;
        AsnConverter elevationConverter = Elevation.CONV;
        CONV.setComponentConverters(new AsnConverter[]{latConverter, long_Converter, elevationConverter});
    }

    @NotNull
    @Component(0)
    public Integer lat;
    @NotNull
    @Component(1)
    public Integer long_;
    @Null
    @Component(2)
    public Integer elevation;    /* OPTIONAL */

    public static Position3D ber_decode(InputStream in) throws IOException {
        return (Position3D) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static Position3D per_decode(boolean align, InputStream in) throws IOException {
        return (Position3D) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof Position3D)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
