/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "DefMotion"
 */
package com.hisense.hiatmp.asn.v2x.VehSafetyExt;

import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.ReflectionEnumeratedConverter;
import org.asnlab.asndt.runtime.type.AsnType;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public enum SpeedConfidence {
    unavailable(0),
    prec100ms(1),
    prec10ms(2),
    prec5ms(3),
    prec1ms(4),
    prec0_1ms(5),
    prec0_05ms(6),
    prec0_01ms(7);

    public final static AsnType TYPE = VehSafetyExt.type(196633);
    public final static AsnConverter CONV;

    static {
        CONV = new ReflectionEnumeratedConverter(SpeedConfidence.class);
    }

    private int value;

    private SpeedConfidence(int value) {
        this.value = value;
    }

    public static SpeedConfidence valueOf(int value) {
        SpeedConfidence[] values = values();
        for (int i = 0; i < values.length; i++) {
            if (values[i].value == value) {
                return values[i];
            }
        }
        throw new IllegalArgumentException("No enum const value for " + value);
    }

    public static SpeedConfidence ber_decode(InputStream in) throws IOException {
        return (SpeedConfidence) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static SpeedConfidence per_decode(boolean align, InputStream in) throws IOException {
        return (SpeedConfidence) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public int value() {
        return value;
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
