/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "VehClass"
 */
package com.hisense.hiatmp.asn.v2x.VehClass;

import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.type.AsnType;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class BasicVehicleClass {


    public final static AsnType TYPE = VehClass.type(65537);
    public final static AsnConverter CONV = IntegerConverter.INSTANCE;
    public final static Integer unknownVehicleClass = (Integer) VehClass.value(65538, CONV);
    public final static Integer specialVehicleClass = (Integer) VehClass.value(65539, CONV);
    public final static Integer passenger_Vehicle_TypeUnknown = (Integer) VehClass.value(65540, CONV);
    public final static Integer passenger_Vehicle_TypeOther = (Integer) VehClass.value(65541, CONV);
    public final static Integer lightTruck_Vehicle_TypeUnknown = (Integer) VehClass.value(65542, CONV);
    public final static Integer lightTruck_Vehicle_TypeOther = (Integer) VehClass.value(65543, CONV);
    public final static Integer truck_Vehicle_TypeUnknown = (Integer) VehClass.value(65544, CONV);
    public final static Integer truck_Vehicle_TypeOther = (Integer) VehClass.value(65545, CONV);
    public final static Integer truck_axleCnt2 = (Integer) VehClass.value(65546, CONV);
    public final static Integer truck_axleCnt3 = (Integer) VehClass.value(65547, CONV);
    public final static Integer truck_axleCnt4 = (Integer) VehClass.value(65548, CONV);
    public final static Integer truck_axleCnt4Trailer = (Integer) VehClass.value(65549, CONV);
    public final static Integer truck_axleCnt5Trailer = (Integer) VehClass.value(65550, CONV);
    public final static Integer truck_axleCnt6Trailer = (Integer) VehClass.value(65551, CONV);
    public final static Integer truck_axleCnt5MultiTrailer = (Integer) VehClass.value(65552, CONV);
    public final static Integer truck_axleCnt6MultiTrailer = (Integer) VehClass.value(65553, CONV);
    public final static Integer truck_axleCnt7MultiTrailer = (Integer) VehClass.value(65554, CONV);
    public final static Integer motorcycle_TypeUnknown = (Integer) VehClass.value(65555, CONV);
    public final static Integer motorcycle_TypeOther = (Integer) VehClass.value(65556, CONV);
    public final static Integer motorcycle_Cruiser_Standard = (Integer) VehClass.value(65557, CONV);
    public final static Integer motorcycle_SportUnclad = (Integer) VehClass.value(65558, CONV);
    public final static Integer motorcycle_SportTouring = (Integer) VehClass.value(65559, CONV);
    public final static Integer motorcycle_SuperSport = (Integer) VehClass.value(65560, CONV);
    public final static Integer motorcycle_Touring = (Integer) VehClass.value(65561, CONV);
    public final static Integer motorcycle_Trike = (Integer) VehClass.value(65562, CONV);
    public final static Integer motorcycle_wPassengers = (Integer) VehClass.value(65563, CONV);
    public final static Integer transit_TypeUnknown = (Integer) VehClass.value(65564, CONV);
    public final static Integer transit_TypeOther = (Integer) VehClass.value(65565, CONV);
    public final static Integer transit_BRT = (Integer) VehClass.value(65566, CONV);
    public final static Integer transit_ExpressBus = (Integer) VehClass.value(65567, CONV);
    public final static Integer transit_LocalBus = (Integer) VehClass.value(65568, CONV);
    public final static Integer transit_SchoolBus = (Integer) VehClass.value(65569, CONV);
    public final static Integer transit_FixedGuideway = (Integer) VehClass.value(65570, CONV);
    public final static Integer transit_Paratransit = (Integer) VehClass.value(65571, CONV);
    public final static Integer transit_Paratransit_Ambulance = (Integer) VehClass.value(65572, CONV);
    public final static Integer emergency_TypeUnknown = (Integer) VehClass.value(65573, CONV);
    public final static Integer emergency_TypeOther = (Integer) VehClass.value(65574, CONV);
    public final static Integer emergency_Fire_Light_Vehicle = (Integer) VehClass.value(65575, CONV);
    public final static Integer emergency_Fire_Heavy_Vehicle = (Integer) VehClass.value(65576, CONV);
    public final static Integer emergency_Fire_Paramedic_Vehicle = (Integer) VehClass.value(65577, CONV);
    public final static Integer emergency_Fire_Ambulance_Vehicle = (Integer) VehClass.value(65578, CONV);
    public final static Integer emergency_Police_Light_Vehicle = (Integer) VehClass.value(65579, CONV);
    public final static Integer emergency_Police_Heavy_Vehicle = (Integer) VehClass.value(65580, CONV);
    public final static Integer emergency_Other_Responder = (Integer) VehClass.value(65581, CONV);
    public final static Integer emergency_Other_Ambulance = (Integer) VehClass.value(65582, CONV);
    public final static Integer otherTraveler_TypeUnknown = (Integer) VehClass.value(65583, CONV);
    public final static Integer otherTraveler_TypeOther = (Integer) VehClass.value(65584, CONV);
    public final static Integer otherTraveler_Pedestrian = (Integer) VehClass.value(65585, CONV);
    public final static Integer otherTraveler_Visually_Disabled = (Integer) VehClass.value(65586, CONV);
    public final static Integer otherTraveler_Physically_Disabled = (Integer) VehClass.value(65587, CONV);
    public final static Integer otherTraveler_Bicycle = (Integer) VehClass.value(65588, CONV);
    public final static Integer otherTraveler_Vulnerable_Roadworker = (Integer) VehClass.value(65589, CONV);
    public final static Integer infrastructure_TypeUnknown = (Integer) VehClass.value(65590, CONV);
    public final static Integer infrastructure_Fixed = (Integer) VehClass.value(65591, CONV);
    public final static Integer infrastructure_Movable = (Integer) VehClass.value(65592, CONV);
    public final static Integer equipped_CargoTrailer = (Integer) VehClass.value(65593, CONV);

    public static void ber_encode(Integer object, OutputStream out) throws IOException {
        TYPE.encode(object, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public static Integer ber_decode(InputStream in) throws IOException {
        return (Integer) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static void per_encode(Integer object, boolean align, OutputStream out) throws IOException {
        TYPE.encode(object, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }

    public static Integer per_decode(boolean align, InputStream in) throws IOException {
        return (Integer) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }


}
