/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "BSM"
 */
package com.hisense.hiatmp.asn.v2x.MsgFrame;

import com.hisense.hiatmp.asn.v2x.AsnV2x;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * @author zhangyong
 */
public class BasicSafetyMessage implements AsnV2x {

    public final static AsnType TYPE = MsgFrame.type(65537);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(BasicSafetyMessage.class);
        AsnConverter msgCntConverter = MsgCount.CONV;
        AsnConverter idConverter = OctetStringConverter.INSTANCE;
        AsnConverter secMarkConverter = DSecond.CONV;
        AsnConverter timeConfidenceConverter = TimeConfidence.CONV;
        AsnConverter posConverter = Position3D.CONV;
        AsnConverter posAccuracyConverter = PositionalAccuracy.CONV;
        AsnConverter posConfidenceConverter = PositionConfidenceSet.CONV;
        AsnConverter transmissionConverter = TransmissionState.CONV;
        AsnConverter speedConverter = Speed.CONV;
        AsnConverter headingConverter = Heading.CONV;
        AsnConverter angleConverter = SteeringWheelAngle.CONV;
        AsnConverter motionCfdConverter = MotionConfidenceSet.CONV;
        AsnConverter accelSetConverter = AccelerationSet4Way.CONV;
        AsnConverter brakesConverter = BrakeSystemStatus.CONV;
        AsnConverter sizeConverter = VehicleSize.CONV;
        AsnConverter vehicleClassConverter = VehicleClassification.CONV;
        AsnConverter safetyExtConverter = VehicleSafetyExtensions.CONV;
        AsnConverter emergencyExtConverter = VehicleEmergencyExtensions.CONV;
        CONV.setComponentConverters(new AsnConverter[]{msgCntConverter, idConverter, secMarkConverter, timeConfidenceConverter, posConverter, posAccuracyConverter, posConfidenceConverter, transmissionConverter, speedConverter, headingConverter, angleConverter, motionCfdConverter, accelSetConverter, brakesConverter, sizeConverter, vehicleClassConverter, safetyExtConverter, emergencyExtConverter});
    }

    @NotNull
    @Component(0)
    public Integer msgCnt;
    @NotNull
    @Size(min = 8, max = 8)
    @Component(1)
    public byte[] id;
    @NotNull
    @Component(2)
    public Integer secMark;
    /**
     * OPTIONAL
     */
    @Null
    @Component(3)
    public TimeConfidence timeConfidence;
    @NotNull
    @Component(4)
    public Position3D pos;
    /**
     * OPTIONAL
     */
    @Null
    @Component(5)
    public PositionalAccuracy posAccuracy;
    /**
     * OPTIONAL
     */
    @Null
    @Component(6)
    public PositionConfidenceSet posConfidence;
    @NotNull
    @Component(7)
    public TransmissionState transmission;
    @NotNull
    @Component(8)
    public Integer speed;
    @NotNull
    @Component(9)
    public Integer heading;
    /**
     * OPTIONAL
     */
    @Null
    @Component(10)
    public Integer angle;
    /**
     * OPTIONAL
     */
    @Null
    @Component(11)
    public MotionConfidenceSet motionCfd;
    @NotNull
    @Component(12)
    public AccelerationSet4Way accelSet;
    @NotNull
    @Component(13)
    public BrakeSystemStatus brakes;
    @NotNull
    @Component(14)
    public VehicleSize size;
    @NotNull
    @Component(15)
    public VehicleClassification vehicleClass;
    /**
     * OPTIONAL
     */
    @Null
    @Component(16)
    public VehicleSafetyExtensions safetyExt;
    /**
     * OPTIONAL
     */
    @Null
    @Component(17)
    public VehicleEmergencyExtensions emergencyExt;

    public static BasicSafetyMessage ber_decode(InputStream in) throws IOException {
        return (BasicSafetyMessage) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static BasicSafetyMessage per_decode(boolean align, InputStream in) throws IOException {
        return (BasicSafetyMessage) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof BasicSafetyMessage)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"msgCnt\":")
                .append(msgCnt);
        sb.append(",\"id\":")
                .append(new String(id));
        sb.append(",\"secMark\":")
                .append(secMark);
        sb.append(",\"timeConfidence\":")
                .append(timeConfidence);
        sb.append(",\"pos\":")
                .append(pos);
        sb.append(",\"posAccuracy\":")
                .append(posAccuracy);
        sb.append(",\"posConfidence\":")
                .append(posConfidence);
        sb.append(",\"transmission\":")
                .append(transmission);
        sb.append(",\"speed\":")
                .append(speed);
        sb.append(",\"heading\":")
                .append(heading);
        sb.append(",\"angle\":")
                .append(angle);
        sb.append(",\"motionCfd\":")
                .append(motionCfd);
        sb.append(",\"accelSet\":")
                .append(accelSet);
        sb.append(",\"brakes\":")
                .append(brakes);
        sb.append(",\"size\":")
                .append(size);
        sb.append(",\"vehicleClass\":")
                .append(vehicleClass);
        sb.append(",\"safetyExt\":")
                .append(safetyExt);
        sb.append(",\"emergencyExt\":")
                .append(emergencyExt);
        sb.append('}');
        return sb.toString();
    }


}
