/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "DefPosition"
 */
package com.hisense.hiatmp.asn.v2x.MsgFrame;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * @author zhangyong
 */
public class PositionalAccuracy {

    public final static AsnType TYPE = MsgFrame.type(262153);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(PositionalAccuracy.class);
        AsnConverter semiMajorConverter = SemiMajorAxisAccuracy.CONV;
        AsnConverter semiMinorConverter = SemiMinorAxisAccuracy.CONV;
        AsnConverter orientationConverter = SemiMajorAxisOrientation.CONV;
        CONV.setComponentConverters(new AsnConverter[]{semiMajorConverter, semiMinorConverter, orientationConverter});
    }

    @NotNull
    @Component(0)
    public Integer semiMajor;
    @NotNull
    @Component(1)
    public Integer semiMinor;
    @NotNull
    @Component(2)
    public Integer orientation;

    public static PositionalAccuracy ber_decode(InputStream in) throws IOException {
        return (PositionalAccuracy) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static PositionalAccuracy per_decode(boolean align, InputStream in) throws IOException {
        return (PositionalAccuracy) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof PositionalAccuracy)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"semiMajor\":")
                .append(semiMajor);
        sb.append(",\"semiMinor\":")
                .append(semiMinor);
        sb.append(",\"orientation\":")
                .append(orientation);
        sb.append('}');
        return sb.toString();
    }
}
