/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "DefPosition"
 */
package com.hisense.hiatmp.asn.v2x.MsgFrame;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * @author zhangyong
 */
public class Position3D {

    public final static AsnType TYPE = MsgFrame.type(262149);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(Position3D.class);
        AsnConverter latConverter = Latitude.CONV;
        AsnConverter long_Converter = Longitude.CONV;
        AsnConverter elevationConverter = Elevation.CONV;
        CONV.setComponentConverters(new AsnConverter[]{latConverter, long_Converter, elevationConverter});
    }

    @NotNull
    @Component(0)
    public Integer lat;
    @NotNull
    @Component(1)
    public Integer long_;
    /**
     * OPTIONAL
     */
    @Null
    @Component(2)
    public Integer elevation;

    public static Position3D ber_decode(InputStream in) throws IOException {
        return (Position3D) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static Position3D per_decode(boolean align, InputStream in) throws IOException {
        return (Position3D) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Position3D)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"lat\":")
                .append(lat);
        sb.append(",\"long_\":")
                .append(long_);
        sb.append(",\"elevation\":")
                .append(elevation);
        sb.append('}');
        return sb.toString();
    }
}
