/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "RSI"
 */
package com.hisense.hiatmp.asn.v2x.MsgFrame;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.Vector;

/**
 * @author zhangyong
 */
public class RTSData {

    public final static AsnType TYPE = MsgFrame.type(1507488);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(RTSData.class);
        AsnConverter rtsIdConverter = IntegerConverter.INSTANCE;
        AsnConverter signTypeConverter = SignType.CONV;
        AsnConverter signPosConverter = PositionOffsetLLV.CONV;
        AsnConverter descriptionConverter = Description.CONV;
        AsnConverter timeDetailsConverter = RSITimeDetails.CONV;
        AsnConverter priorityConverter = RSIPriority.CONV;
        AsnConverter referencePathsConverter = ReferencePathList.CONV;
        AsnConverter referenceLinksConverter = ReferenceLinkList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{rtsIdConverter, signTypeConverter, signPosConverter, descriptionConverter, timeDetailsConverter, priorityConverter, referencePathsConverter, referenceLinksConverter});
    }

    @NotNull
    @Min(0L)
    @Max(255L)
    @Component(0)
    public Integer rtsId;
    @NotNull
    @Component(1)
    public Integer signType;
    /**
     * OPTIONAL
     */
    @Null
    @Component(2)
    public PositionOffsetLLV signPos;
    /**
     * OPTIONAL
     */
    @Null
    @Component(3)
    public Description description;
    /**
     * OPTIONAL
     */
    @Null
    @Component(4)
    public RSITimeDetails timeDetails;
    /**
     * OPTIONAL
     */
    @Null
    @Component(5)
    public byte[] priority;
    /**
     * OPTIONAL
     */
    @Null
    @Component(6)
    public Vector<ReferencePath> referencePaths;
    /**
     * OPTIONAL
     */
    @Null
    @Component(7)
    public Vector<ReferenceLink> referenceLinks;

    public static RTSData ber_decode(InputStream in) throws IOException {
        return (RTSData) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static RTSData per_decode(boolean align, InputStream in) throws IOException {
        return (RTSData) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof RTSData)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"rtsId\":")
                .append(rtsId);
        sb.append(",\"signType\":")
                .append(signType);
        sb.append(",\"signPos\":")
                .append(signPos);
        sb.append(",\"description\":")
                .append(description);
        sb.append(",\"timeDetails\":")
                .append(timeDetails);
        sb.append(",\"priority\":")
                .append(Arrays.toString(priority));
        sb.append(",\"referencePaths\":")
                .append(referencePaths);
        sb.append(",\"referenceLinks\":")
                .append(referenceLinks);
        sb.append('}');
        return sb.toString();
    }
}
