/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "SignalPhaseAndTiming"
 */
package com.hisense.hiatmp.asn.v2x.MsgFrame;

import com.hisense.hiatmp.asn.v2x.AsnV2x;
import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

/**
 * @author zhangyong
 */
public class SPAT implements AsnV2x {

    public final static AsnType TYPE = MsgFrame.type(1441923);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(SPAT.class);
        AsnConverter msgCntConverter = MsgCount.CONV;
        AsnConverter moyConverter = MinuteOfTheYear.CONV;
        AsnConverter timeStampConverter = DSecond.CONV;
        AsnConverter nameConverter = DescriptiveName.CONV;
        AsnConverter intersectionsConverter = IntersectionStateList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{msgCntConverter, moyConverter, timeStampConverter, nameConverter, intersectionsConverter});
    }

    @NotNull
    @Component(0)
    public Integer msgCnt;
    @Null
    @Component(1)
    /** OPTIONAL **/
    public Integer moy;
    @Null
    @Component(2)
    /** OPTIONAL **/
    public Integer timeStamp;
    @Null
    @Component(3)
    /** OPTIONAL **/
    public String name;
    @NotNull
    @Component(4)
    public Vector<IntersectionState> intersections;

    public static SPAT ber_decode(InputStream in) throws IOException {
        return (SPAT) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static SPAT per_decode(boolean align, InputStream in) throws IOException {
        return (SPAT) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SPAT)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"msgCnt\":")
                .append(msgCnt);
        sb.append(",\"moy\":")
                .append(moy);
        sb.append(",\"timeStamp\":")
                .append(timeStamp);
        sb.append(",\"name\":\"")
                .append(name).append('\"');
        sb.append(",\"intersections\":")
                .append(intersections);
        sb.append('}');
        return sb.toString();
    }
}
