/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "SPATIntersectionState"
 */
package com.hisense.hiatmp.asn.v2x.SignalPhaseAndTiming;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class PhaseState {

    public final static AsnType TYPE = SignalPhaseAndTiming.type(262160);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(PhaseState.class);
        AsnConverter lightConverter = LightState.CONV;
        AsnConverter timingConverter = TimeChangeDetails.CONV;
        CONV.setComponentConverters(new AsnConverter[]{lightConverter, timingConverter});
    }

    @NotNull
    @Component(0)
    public LightState light;
    @Null
    @Component(1)
    public TimeChangeDetails timing;    /* OPTIONAL */

    public static PhaseState ber_decode(InputStream in) throws IOException {
        return (PhaseState) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static PhaseState per_decode(boolean align, InputStream in) throws IOException {
        return (PhaseState) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof PhaseState)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
