/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "SignalPhaseAndTiming"
 */
package com.hisense.hiatmp.asn.v2x.SignalPhaseAndTiming;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

public class SPAT {

    public final static AsnType TYPE = SignalPhaseAndTiming.type(393239);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(SPAT.class);
        AsnConverter msgCntConverter = MsgCount.CONV;
        AsnConverter moyConverter = MinuteOfTheYear.CONV;
        AsnConverter timeStampConverter = DSecond.CONV;
        AsnConverter nameConverter = DescriptiveName.CONV;
        AsnConverter intersectionsConverter = IntersectionStateList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{msgCntConverter, moyConverter, timeStampConverter, nameConverter, intersectionsConverter});
    }

    @NotNull
    @Component(0)
    public Integer msgCnt;
    @Null
    @Component(1)
    public Integer moy;    /* OPTIONAL */
    @Null
    @Component(2)
    public Integer timeStamp;    /* OPTIONAL */
    @Null
    @Component(3)
    public String name;    /* OPTIONAL */
    @NotNull
    @Component(4)
    public Vector<IntersectionState> intersections;

    public static SPAT ber_decode(InputStream in) throws IOException {
        return (SPAT) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static SPAT per_decode(boolean align, InputStream in) throws IOException {
        return (SPAT) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof SPAT)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
