/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "SPATIntersectionState"
 */
package com.hisense.hiatmp.asn.v2x.SignalPhaseAndTiming;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class UTCTiming {

    public final static AsnType TYPE = SignalPhaseAndTiming.type(262166);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(UTCTiming.class);
        AsnConverter startUTCTimeConverter = TimeMark.CONV;
        AsnConverter minEndUTCTimeConverter = TimeMark.CONV;
        AsnConverter maxEndUTCTimeConverter = TimeMark.CONV;
        AsnConverter likelyEndUTCTimeConverter = TimeMark.CONV;
        AsnConverter timeConfidenceConverter = Confidence.CONV;
        AsnConverter nextStartUTCTimeConverter = TimeMark.CONV;
        AsnConverter nextEndUTCTimeConverter = TimeMark.CONV;
        CONV.setComponentConverters(new AsnConverter[]{startUTCTimeConverter, minEndUTCTimeConverter, maxEndUTCTimeConverter, likelyEndUTCTimeConverter, timeConfidenceConverter, nextStartUTCTimeConverter, nextEndUTCTimeConverter});
    }

    @NotNull
    @Component(0)
    public Integer startUTCTime;
    @Null
    @Component(1)
    public Integer minEndUTCTime;    /* OPTIONAL */
    @Null
    @Component(2)
    public Integer maxEndUTCTime;    /* OPTIONAL */
    @NotNull
    @Component(3)
    public Integer likelyEndUTCTime;
    @Null
    @Component(4)
    public Integer timeConfidence;    /* OPTIONAL */
    @Null
    @Component(5)
    public Integer nextStartUTCTime;    /* OPTIONAL */
    @Null
    @Component(6)
    public Integer nextEndUTCTime;    /* OPTIONAL */

    public static UTCTiming ber_decode(InputStream in) throws IOException {
        return (UTCTiming) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static UTCTiming per_decode(boolean align, InputStream in) throws IOException {
        return (UTCTiming) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof UTCTiming)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
