/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "SPATIntersectionState"
 */
package com.hisense.hiatmp.asn.v2x.SPATIntersectionState;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

public class IntersectionState {

    public final static AsnType TYPE = SPATIntersectionState.type(65555);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(IntersectionState.class);
        AsnConverter intersectionIdConverter = NodeReferenceID.CONV;
        AsnConverter statusConverter = IntersectionStatusObject.CONV;
        AsnConverter moyConverter = MinuteOfTheYear.CONV;
        AsnConverter timeStampConverter = DSecond.CONV;
        AsnConverter timeConfidenceConverter = TimeConfidence.CONV;
        AsnConverter phasesConverter = PhaseList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{intersectionIdConverter, statusConverter, moyConverter, timeStampConverter, timeConfidenceConverter, phasesConverter});
    }

    @NotNull
    @Component(0)
    public NodeReferenceID intersectionId;
    @NotNull
    @Component(1)
    public IntersectionStatusObject status;
    @Null
    @Component(2)
    public Integer moy;    /* OPTIONAL */
    @Null
    @Component(3)
    public Integer timeStamp;    /* OPTIONAL */
    @Null
    @Component(4)
    public TimeConfidence timeConfidence;    /* OPTIONAL */
    @NotNull
    @Component(5)
    public Vector<Phase> phases;

    public static IntersectionState ber_decode(InputStream in) throws IOException {
        return (IntersectionState) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static IntersectionState per_decode(boolean align, InputStream in) throws IOException {
        return (IntersectionState) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof IntersectionState)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
