/*
 * Generated by ASN.1 Java Compiler (https://www.asnlab.org/)
 * From ASN.1 module "SPATIntersectionState"
 */
package com.hisense.hiatmp.asn.v2x.SPATIntersectionState;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

public class Phase {

    public final static AsnType TYPE = SPATIntersectionState.type(65547);
    public final static CompositeConverter CONV;

    static {
        CONV = new AnnotationCompositeConverter(Phase.class);
        AsnConverter idConverter = PhaseID.CONV;
        AsnConverter phaseStatesConverter = PhaseStateList.CONV;
        CONV.setComponentConverters(new AsnConverter[]{idConverter, phaseStatesConverter});
    }

    @NotNull
    @Component(0)
    public Integer id;
    @NotNull
    @Component(1)
    public Vector<PhaseState> phaseStates;

    public static Phase ber_decode(InputStream in) throws IOException {
        return (Phase) TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONV);
    }

    public static Phase per_decode(boolean align, InputStream in) throws IOException {
        return (Phase) TYPE.decode(in, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV);
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof Phase)) {
            return false;
        }
        return TYPE.equals(this, obj, CONV);
    }

    public void ber_encode(OutputStream out) throws IOException {
        TYPE.encode(this, EncodingRules.BASIC_ENCODING_RULES, CONV, out);
    }

    public void per_encode(boolean align, OutputStream out) throws IOException {
        TYPE.encode(this, align ? EncodingRules.ALIGNED_PACKED_ENCODING_RULES : EncodingRules.UNALIGNED_PACKED_ENCODING_RULES, CONV, out);
    }


}
